// Generated by Wrangler by running `wrangler types` (override as needed)
// After running `wrangler types`, replace this file with the generated output.

interface Env {
  FIREBASE_PROJECT_ID: string;
  STRIPE_WEBHOOK_SECRET: string;
  STRIPE_WEBHOOK_SECRET_TEST: string;
  STRIPE_SECRET_KEY: string;
  GCP_CLIENT_EMAIL: string;
  GCP_PRIVATE_KEY: string;
}
